"""ZH4l public naming and the explicit historical comparison vocabulary."""

import re


LEGACY_COLUMN_NAMES = {
    "Z_idx": "z_lepton_index",
    "X_idx": "x_lepton_index",
    "validZ": "z_is_valid",
    "validX": "x_is_valid",
    "validZX": "zx_is_valid",
    "passLeading2Tight": "event_pass_leading_lepton_tight",
    "passZPt": "z_pass_ordered_pt",
    "pass4lPt": "zx_pass_ordered_pt",
    "veto5l": "event_pass_extra_lepton_veto",
    "nLepton10": "veto_lepton_count",
    "noJetInHorn": "event_pass_jet_horn_veto",
    "isZee": "z_is_ee",
    "isZmm": "z_is_mumu",
    "isXee": "x_is_ee",
    "isXmm": "x_is_mumu",
    "isXSF": "x_is_same_flavor",
    "isXDF": "x_is_different_flavor",
    "mZ": "z_mass",
    "ptZ": "z_pt",
    "etaZ": "z_eta",
    "phiZ": "z_phi",
    "mX": "x_mass",
    "ptX": "x_pt",
    "etaX": "x_eta",
    "phiX": "x_phi",
    "m4l": "zx_mass",
    "pt4l": "zx_pt",
    "phi4l": "zx_phi",
    "q4l": "zx_charge",
    "minMll4l": "zx_min_pair_mass",
    "bVeto": "event_pass_b_veto",
    "bVeto30": "event_pass_b_veto_pt30",
    "bVetoSF": "sf_b_veto",
    "dPhiMETZ": "met_z_delta_phi",
    "dPhiMETX": "met_x_delta_phi",
    "dPhiMET4l": "met_zx_delta_phi",
    "recoilUpar": "recoil_u_parallel",
    "recoilUperp": "recoil_u_perpendicular",
    "ZH4l_prodPt": "zh4l_internal_production_lepton_pt",
    "ZH4l_prodPdgId": "zh4l_internal_production_lepton_pdg_id",
    "ZH4l_triggerDeclared": "zh4l_internal_trigger_declared",
    "ZH4l_triggerResultZ": "zh4l_internal_trigger_z_result",
    "ZH4l_triggerResultZX": "zh4l_internal_trigger_zx_result",
    "ZH4l_btagSFbc": "zh4l_internal_sf_btag_bc",
    "ZH4l_btagSFlight": "zh4l_internal_sf_btag_light",
    "ZH4l_sourceFile": "zh4l_internal_source_file",
    "ZH4l_sourceEntry": "zh4l_internal_source_entry",
    "PairingEvent": "zh4l_internal_pairing_result",
    "PairingTightMask": "zh4l_internal_pairing_tight_mask",
    "PairingM4l": "pairing_quartet_mass",
    "PairingMinPairMass": "pairing_quartet_min_pair_mass",
    "QuartetTopology": "pairing_quartet_topology",
    "StudyRawWeight": "weight_raw",
    "StudySignedWeight": "weight_nominal",
    "StudyAbsWeight": "weight_abs_nominal",
    "StudyRawWeightVec": "pairing_weight_raw",
    "StudySignedWeightVec": "pairing_weight_nominal",
    "StudyAbsWeightVec": "pairing_weight_abs_nominal",
    "StudyWeightSign": "event_weight_sign",
    "passAnchor2lPt": "event_pass_anchor_ordered_pt",
    "nExtraTight10": "extra_tight_lepton_count",
    "Z0_absRapidity": "z_abs_rapidity",
    "phiEtaStar": "z_phi_eta_star",
    "Z_lead_pt": "z_lepton_lead_pt",
    "Z_sublead_pt": "z_lepton_sublead_pt",
    "Z_lead_absEta": "z_lepton_lead_abs_eta",
    "Z_sublead_absEta": "z_lepton_sublead_abs_eta",
    "nJet30": "selected_jet_count",
    "nBLoose": "tagged_jet_count",
    "X_flavor_code": "x_flavor_code",
    "selected4lPt1": "zx_lepton_rank1_pt",
    "selected4lPt4": "zx_lepton_rank4_pt",
    "absEta": "lepton_abs_eta",
    "triggerPriority": "event_trigger_priority",
    "streamPriority": "event_stream_priority",
    "streamPriority_MuonEG": "event_stream_is_muoneg",
    "streamPriority_Muon": "event_stream_is_muon",
    "streamPriority_EGamma": "event_stream_is_egamma",
    "LepSF_Z": "sf_lepton_z",
    "LepSF_Z_Up": "sf_lepton_z_up",
    "LepSF_Z_Down": "sf_lepton_z_down",
    "LepSF_Z_EleUp": "sf_lepton_z_electron_up",
    "LepSF_Z_EleDown": "sf_lepton_z_electron_down",
    "LepSF_Z_MuUp": "sf_lepton_z_muon_up",
    "LepSF_Z_MuDown": "sf_lepton_z_muon_down",
    "TriggerSF_Z": "sf_trigger_z",
    "TriggerSF_Z_Up": "sf_trigger_z_up",
    "TriggerSF_Z_Down": "sf_trigger_z_down",
    "TriggerSF_Z_EleUp": "sf_trigger_z_electron_up",
    "TriggerSF_Z_EleDown": "sf_trigger_z_electron_down",
    "TriggerSF_Z_MuUp": "sf_trigger_z_muon_up",
    "TriggerSF_Z_MuDown": "sf_trigger_z_muon_down",
    "LepSF_ZX": "sf_lepton_zx",
    "LepSF_ZX_Up": "sf_lepton_zx_up",
    "LepSF_ZX_Down": "sf_lepton_zx_down",
    "LepSF_ZX_EleUp": "sf_lepton_zx_electron_up",
    "LepSF_ZX_EleDown": "sf_lepton_zx_electron_down",
    "LepSF_ZX_MuUp": "sf_lepton_zx_muon_up",
    "LepSF_ZX_MuDown": "sf_lepton_zx_muon_down",
    "TriggerSF_ZX": "sf_trigger_zx",
    "TriggerSF_ZX_Up": "sf_trigger_zx_up",
    "TriggerSF_ZX_Down": "sf_trigger_zx_down",
    "TriggerSF_ZX_EleUp": "sf_trigger_zx_electron_up",
    "TriggerSF_ZX_EleDown": "sf_trigger_zx_electron_down",
    "TriggerSF_ZX_MuUp": "sf_trigger_zx_muon_up",
    "TriggerSF_ZX_MuDown": "sf_trigger_zx_muon_down",
    "ZH4l_btagSFbc_up_correlated": "zh4l_internal_sf_btag_bc_up_correlated",
    "ZH4l_btagSFbc_down_correlated": "zh4l_internal_sf_btag_bc_down_correlated",
    "ZH4l_btagSFbc_up_uncorrelated": "zh4l_internal_sf_btag_bc_up_uncorrelated",
    "ZH4l_btagSFbc_down_uncorrelated": "zh4l_internal_sf_btag_bc_down_uncorrelated",
    "ZH4l_btagSFlight_up_correlated": "zh4l_internal_sf_btag_light_up_correlated",
    "ZH4l_btagSFlight_down_correlated": "zh4l_internal_sf_btag_light_down_correlated",
    "ZH4l_btagSFlight_up_uncorrelated": "zh4l_internal_sf_btag_light_up_uncorrelated",
    "ZH4l_btagSFlight_down_uncorrelated": "zh4l_internal_sf_btag_light_down_uncorrelated",
    "PairingObjectBase": "pairing_pass_object_base",
    "PairingPhysBase": "pairing_pass_physics_base",
    "PairingQuartetValid": "pairing_quartet_is_valid",
    "PairingSourceAlignmentValid": "pairing_source_alignment_is_valid",
    "PairingSourceAlignmentFailure": "pairing_source_alignment_failure",
    "PairingResolutionScoresValid": "pairing_resolution_scores_are_valid",
    "PairingFSRScoresValid": "pairing_fsr_scores_are_valid",
    "PairingXComplementIdentical": "pairing_x_complement_is_identical",
    "PairingXDifferenceReason": "pairing_x_difference_reason",
    "PairingCandidateMultiplicity": "pairing_candidate_multiplicity",
    "PairingDistinctPartitions": "pairing_distinct_partitions",
    "ZHTruthStatus": "zh_truth_status",
    "ZZTruthStatus": "zz_truth_status",
    "ZHTruthPtZ": "zh_truth_z_pt",
    "ZZTruthPtZ": "zz_truth_z_pt",
    "ZHTruthRecoverable": "zh_truth_is_recoverable",
    "ZZTruthRecoverable": "zz_truth_is_recoverable",
    "ZHTruthDirect": "zh_truth_is_direct",
    "ZZTruthDirect": "zz_truth_is_direct",
    "ZHHWWComplementValid": "zh_hww_complement_is_valid",
    "ZZTruthIdenticalFlavorConvention": "zz_truth_identical_flavor_convention",
    "ZZTruthRecordAmbiguous": "zz_truth_record_is_ambiguous",
    "AlgorithmAxis": "algorithm_axis",
    "QuartetTopologyAxis": "quartet_topology_axis",
    "AlgorithmValidAxis": "algorithm_valid_axis",
    "ZHCorrectAxis": "zh_correct_axis",
    "ZZCorrectAxis": "zz_correct_axis",
    "ZHGainLossAxis": "zh_gain_loss_axis",
    "ZZGainLossAxis": "zz_gain_loss_axis",
    "PairingSelectedCandidateAxis": "pairing_selected_candidate_axis",
    "PairingSelectedZFlavorAxis": "pairing_selected_z_flavor_axis",
    "PairingBestScoreAxis": "pairing_best_score_axis",
    "PairingSecondScoreAxis": "pairing_second_score_axis",
    "PairingMZAxis": "pairing_z_mass_axis",
    "PairingMXAxis": "pairing_x_mass_axis",
    "PairingPtZAxis": "pairing_z_pt_axis",
    "PairingPtXAxis": "pairing_x_pt_axis",
    "PairingDrZAxis": "pairing_z_delta_r_axis",
    "PairingDrXAxis": "pairing_x_delta_r_axis",
    "PairingScoreGapAxis": "pairing_score_gap_axis",
    "PairingRegionAxis": "pairing_region_axis",
    "PairingXFlavorAxis": "pairing_x_flavor_axis",
    "ZHTruthPtZAxis": "zh_truth_z_pt_axis",
    "ZZTruthPtZAxis": "zz_truth_z_pt_axis",
    "ZHPtZResponseAxis": "zh_z_pt_response_axis",
    "ZZPtZResponseAxis": "zz_z_pt_response_axis",
    "ZHTruthStatusAxis": "zh_truth_status_axis",
    "ZZTruthStatusAxis": "zz_truth_status_axis",
    "BaselineCandidateAxis": "baseline_candidate_axis",
    "BaselineRegionAxis": "baseline_region_axis",
    "BaselineXFlavorAxis": "baseline_x_flavor_axis",
}


def public_name(name):
    if not re.fullmatch(r"[a-z][a-z0-9]*(?:_[a-z0-9]+)*", name):
        raise ValueError(f"ZH4l names must use lowercase snake_case: {name!r}")
    return name


def historical_expression(expression):
    """Translate current columns for a preserved historical expression oracle."""
    reverse = {new: old for old, new in LEGACY_COLUMN_NAMES.items()}
    pattern = (
        r"(?<![\w.:])("
        + "|".join(map(re.escape, sorted(reverse, key=len, reverse=True)))
        + r")(?!\w)"
    )
    return re.sub(pattern, lambda match: reverse[match[0]], expression)
